### ISSUE TITLE
bad indention

### ISSUE THREAD

**Issue by Walidmash** [FACG2/world-weather-week5#30]
you guys should correct your indention in https://github.com/FACG2/world-weather-week5/blob/master/src/router.js

**Comment by mahmoudalwadia** [comment]
fixed :metal:

**Comment by Walidmash** [comment]
Its still wrong :3 
look at those lines
[line6](https://github.com/FACG2/world-weather-week5/blob/master/src/router.js#L6
)
[line12](https://github.com/FACG2/world-weather-week5/blob/master/src/router.js#L12
)
